{% set name = "swarp" %}
{% set version = "2.41.5" %}

package:
  name: astromatic-{{ name }}
  version: {{ version }}

source:
  url: https://github.com/astromatic/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 954cebb1e5b1b4f7791b9b38b4e0f07bb2233775a97d6254def5c24b6b5a7f31

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - gnuconfig  # [unix]
    - libtool
    - make

test:
  source_files:
    - test
  commands:
    - cd test
    - swarp -d > default.swarp
    - swarp test.fits -c default.swarp

about:
  home: https://www.astromatic.net/software/swarp
  license: GPL-3.0-only
  license_file: COPYRIGHT
  summary: |
    SWarp is a program that resamples and co-adds together FITS images
    using any arbitrary astrometric projection defined in the WCS standard

extra:
  recipe-maintainers:
    - drbixx
    - teake
