travis:
  secure:
    BINSTAR_TOKEN: ZkXw8JvQRsu2CoMYpTgk64PeE2Nn18xPoqdmTObRr3ZcuCA/6ubsOhpTib3Vc/7NT0p6aPpVqRu/prpWhHfZu8Sr+oWGtp4KbPMTAb7U5UBEihRjNy5g7KBAjuS1Yj1AALS4y4bOkQYjk0ot6NXDzeAe0vFxVfzqrRkDJVivc9O+bX0ngOvmGldj6mZpZCtgVql5MAEwFfcR9JhBI+FROKsuHAtM0pw82w+hL7PLLKLdTSPIUxtbz8wCS/r/ekjlls2t8lLPLFMq+XPJk7IYneSpMkK7yQlt9FGgSkYwfJ8RqR3jeabSGl4u+gje8bgnky3CJp3fu+2zZ2IZhtN0VFdMgQOWPqE4oC11CzC4/vsA7YZ8vC68VFmoDWi58XHS3eaDfPM9VM5lP4Xz+f2IcW79vFKmsoYV8G94Z8x7At5r+gmzyoWi1O9XxDjsN0IrOk+/ty4JudVzd/JblLJhtdd2XeyCSpv+Jfay36bD/c17ckM50/wLTE0Mql08pXT5R5Koj9w91/NC8o29kd4Dmal0oLZSLLk0dg0nPY2XgLIUafgCNlcUAE7WOoiM56Iw4ma0b0JjdYC+WKjQ2SpxzFSzPLdVC+YfdjPG+PfrqhO7wPeHDyvAeuO7MxQyo++rFDIfiZbtTM0PmoUyPH8JMDJ3ZLpaZGkdbvrE32XzuBw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
